# Generated by Django 4.1.3 on 2025-02-22 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0006_remove_piloto_equipo_imagentarea_nacionalidad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarea',
            name='configuracion',
        ),
    ]
