# Generated by Django 4.1.3 on 2025-02-22 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0007_remove_tarea_configuracion'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='configuracion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
