# Generated by Django 4.1.3 on 2025-02-22 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0008_tarea_configuracion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultadocarrera',
            name='posicion',
            field=models.TextField(),
        ),
    ]
