# Generated by Django 4.1.3 on 2025-02-23 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0009_alter_resultadocarrera_posicion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resultadocarrera',
            name='Vuelta_Rapida',
        ),
        migrations.RemoveField(
            model_name='resultadocarrera',
            name='posicion',
        ),
    ]
