# Generated by Django 4.1.3 on 2025-02-23 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0010_remove_resultadocarrera_vuelta_rapida_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resultadocarrera',
            name='puntos',
        ),
        migrations.AddField(
            model_name='resultadocarrera',
            name='cat',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='resultadocarrera',
            name='dragon',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='resultadocarrera',
            name='grand',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='resultadocarrera',
            name='kioto',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='resultadocarrera',
            name='lago',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='resultadocarrera',
            name='mount',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='resultadocarrera',
            name='spa',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='resultadocarrera',
            name='suzuka',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='resultadocarrera',
            name='tokio',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='resultadocarrera',
            name='trial',
            field=models.IntegerField(null=True),
        ),
    ]
