# Generated by Django 4.1.3 on 2025-03-19 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0011_remove_resultadocarrera_puntos_resultadocarrera_cat_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resultadocarrera',
            old_name='cat',
            new_name='Interlagos',
        ),
        migrations.RenameField(
            model_name='resultadocarrera',
            old_name='dragon',
            new_name='daytona',
        ),
        migrations.RenameField(
            model_name='resultadocarrera',
            old_name='grand',
            new_name='lemans',
        ),
        migrations.RenameField(
            model_name='resultadocarrera',
            old_name='kioto',
            new_name='watkins',
        ),
        migrations.RemoveField(
            model_name='resultadocarrera',
            name='lago',
        ),
        migrations.RemoveField(
            model_name='resultadocarrera',
            name='mount',
        ),
        migrations.RemoveField(
            model_name='resultadocarrera',
            name='tokio',
        ),
        migrations.RemoveField(
            model_name='resultadocarrera',
            name='trial',
        ),
    ]
