# Generated by Django 4.1.3 on 2025-03-21 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0013_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitas',
            name='usuario',
        ),
    ]
