# Generated by Django 4.1.3 on 2025-03-25 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0014_remove_visitas_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resultadocarrera',
            old_name='Interlagos',
            new_name='alemania',
        ),
        migrations.RemoveField(
            model_name='resultadocarrera',
            name='foto_circuito',
        ),
        migrations.AddField(
            model_name='resultadocarrera',
            name='alsace',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='resultadocarrera',
            name='austria',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='resultadocarrera',
            name='blue_moon',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='resultadocarrera',
            name='brasil',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='resultadocarrera',
            name='california',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='resultadocarrera',
            name='canada',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='resultadocarrera',
            name='españa',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='resultadocarrera',
            name='fishermans',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='resultadocarrera',
            name='fuji',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='resultadocarrera',
            name='high_speed',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='resultadocarrera',
            name='inglaterra',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='resultadocarrera',
            name='italia',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='resultadocarrera',
            name='m_panorama',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='resultadocarrera',
            name='monterey',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='resultadocarrera',
            name='nurburgring',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='resultadocarrera',
            name='suiza',
            field=models.IntegerField(null=True),
        ),
    ]
