# Generated by Django 4.1.3 on 2025-04-05 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0017_sancion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sancion',
            old_name='monto',
            new_name='perdida_puntos',
        ),
    ]
