# Generated by Django 4.1.3 on 2025-04-05 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0018_rename_monto_sancion_perdida_puntos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sancion',
        ),
    ]
