# Generated by Django 4.1.3 on 2025-05-02 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0019_delete_sancion'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='image_file',
            field=models.ImageField(null=True, upload_to='videos/'),
        ),
    ]
