# Generated by Django 4.1.3 on 2025-02-21 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0002_carrera_equipo_imagenavatar_modelo_piloto_proveedor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagentarea',
            old_name='carrera',
            new_name='carreras',
        ),
    ]
