# Generated by Django 4.1.3 on 2025-02-21 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0003_rename_carrera_imagentarea_carreras'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagentarea',
            name='carreras',
        ),
    ]
