# Generated by Django 4.1.3 on 2025-02-21 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0004_remove_imagentarea_carreras'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagentarea',
            name='carrera',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='tareas.tarea'),
        ),
    ]
