# Generated by Django 4.1.3 on 2025-02-21 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0005_imagentarea_carrera'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='piloto',
            name='equipo',
        ),
        migrations.AddField(
            model_name='imagentarea',
            name='nacionalidad',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='imagentarea',
            name='nombre',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.DeleteModel(
            name='Equipo',
        ),
    ]
